services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
    ports:
      - "4000:4000"
    # No depends_on db because we use RDS

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
      BACKEND_API_URL: "http://api:4000/api/v1"
    depends_on:
      - api
    ports:
      - "3000:3000"

  ai-service:
    build:
      context: .
      dockerfile: Dockerfile.ai
    env_file:
      - .env.prod
    environment:
      API_CORE_BASE_URL: "http://api:4000/api/v1"
    ports:
      - "8000:8000"

  scraper-service:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    env_file:
      - .env.prod
    environment:
      API_CORE_BASE_URL: "http://api:4000/api/v1"
    ports:
      - "8100:8100"

  jarvis-backend:
    build:
      context: .
      dockerfile: Dockerfile.jarvis
    env_file:
      - .env.prod
    environment:
      API_CORE_BASE_URL: "http://api:4000/api/v1"
    ports:
      - "8200:8200"
  # DB Service removed because we are using AWS RDS
